//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesErrosMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesErrosMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCommerce.Exceptions.ResourcesErrosMessages", typeof(ResourcesErrosMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não é válido.
        /// </summary>
        public static string ERRO_EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("ERRO_EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não pode estar em branco.
        /// </summary>
        public static string ERRO_EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("ERRO_EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode estar vazio.
        /// </summary>
        public static string ERRO_NOME_VAZIO {
            get {
                return ResourceManager.GetString("ERRO_NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não é valida. Por gentileza fornecer uma senha com no mínimo 6 dígitos, contendo pelo menos um caractere especial.
        /// </summary>
        public static string ERRO_SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("ERRO_SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode estar em branco.
        /// </summary>
        public static string ERRO_SENHA_VAZIA {
            get {
                return ResourceManager.GetString("ERRO_SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone não é válido. Por gentileza fornecer um número no formato XX X XXXX-XXXX.
        /// </summary>
        public static string ERRO_TELEFONE_INVALIDO {
            get {
                return ResourceManager.GetString("ERRO_TELEFONE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone não pode estar em branco.
        /// </summary>
        public static string ERRO_TELEFONE_VAZIO {
            get {
                return ResourceManager.GetString("ERRO_TELEFONE_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errodesconhecido. Entrar em contato com o desenvolvedor..
        /// </summary>
        public static string ERRRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o e-mail fornecido já está cadastrado. Por gentileza, envie um e-mail válido.
        /// </summary>
        public static string ERRRO_EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("ERRRO_EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
    }
}
